- name: get token
  gather_facts: No
  any_errors_fatal: true
  hosts: _dev
  #become: true
  vars:
    ansible_become_method: doas # image olarak alpine imge kullandığımızda sudo yerine "doas" kullanmamızı istemişti, onun için bu satırı ekledik...
  tasks:
#   - name: add taint to server node
#     shell: kubectl taint nodes $(doas kubectl get no | grep master | awk '{print $1}') nginx=nomaster:NoSchedule
#   - name: add label to server node
#     shell: kubectl label nodes $(doas kubectl get no | grep master | awk '{print $1}') master=db
  - name: copy file
    copy:
      src: "./gitlab-admin-service-account.yaml"
      dest: /home/alpine/gitlab-admin-service-account.yaml
  - name: create service account
    shell: kubectl apply -f /home/alpine/gitlab-admin-service-account.yaml
  - name: get token
    shell: kubectl -n kube-system describe secret $(doas kubectl -n kube-system get secret | grep gitlab | awk '{print $1}') | grep -A15 "gitlab-token"  | tail -1 | awk '{print $2}'
    register: auth_token
  - debug: msg='{{ auth_token.stdout.strip() }}'
